# Generated by Django 3.1.7 on 2021-03-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='show',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
